import type { Meta, StoryObj } from '@storybook/react';
import type { ButtonProps } from '../components/Button';
declare const meta: Meta<ButtonProps>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Outline: Story;
export declare const Menu: Story;
export declare const MenuItem: Story;
export declare const Topic: Story;
export declare const WithStartIcon: Story;
export declare const WithEndIcon: Story;
export declare const Disabled: Story;
export declare const AsLink: Story;
