import type { Meta, StoryObj } from '@storybook/react';
import { InputProps } from '../components/Input';
declare const meta: Meta<InputProps>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Email: Story;
export declare const Textarea: Story;
export declare const WhiteColor: Story;
export declare const WithError: Story;
